// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// image //
// ----- //

#define image_wrap_target 0
#define image_wrap 6

static const uint16_t image_program_instructions[] = {
            //     .wrap_target
    0x2028, //  0: wait   0 pin, 8                   
    0x20a8, //  1: wait   1 pin, 8                   
    0x20a9, //  2: wait   1 pin, 9                   
    0x20aa, //  3: wait   1 pin, 10                  
    0x4008, //  4: in     pins, 8                    
    0x202a, //  5: wait   0 pin, 10                  
    0x0002, //  6: jmp    2                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program image_program = {
    .instructions = image_program_instructions,
    .length = 7,
    .origin = -1,
};

static inline pio_sm_config image_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + image_wrap_target, offset + image_wrap);
    return c;
}
#endif
